---
title: "___"
author: "___"
date: "___"
output: html_document
---

```{r setup}

```

```{r import}

```

<!--% Explorez vos données ici. Vous devez réaliser 12 graphiques ou tableaux (environ 3 par étudiant, un commit dans GitHub permettant de voir clairement qui a fait quoi). Chaque graphique ou tableau doit être interprété en maximum 5 phrases. N'utilisez pas de titres entre les items et les paragraphes qui les interprètent qui doivent se situer en dessous d'eux, pas au dessus. Les interprétations doivent être faites dans des paragraphes Markdown correctement formatés. --> 

<!--% Chaque graphique doit avoir des labels et des unités corrects et en français. -->

<!--% Pour les tableaux, ceux reprenant simplement les données brutes ou une partie d'entre elles ne sont pas admis. Il faut obligatoirement des tableaux de synthèse. Soignez-en la présentation et les titres des colonnes qui doivent être en français. -->

<!--% L'ensemble de vos tableaux et graphiques doivent former un déroulement le long d'un fil conducteur qui amène le lecteur à mieux comprendre les données en relation étroite avec la question de recherche définie dans `state_of_art.Rmd`. Un ensemble au hasard et incohérent d'items n'est PAS valable ici ! -->

```{r item1}

```

<!--# Interprétation de l'item 1 -->


```{r item2}

```

<!--# Interprétation de l'item 2 -->


```{r item3}

```

<!--# Interprétation de l'item 3 -->


```{r item4}

```

<!--# Interprétation de l'item 4 -->


```{r item5}

```

<!--# Interprétation de l'item 5 -->


```{r item6}

```

<!--# Interprétation de l'item 6 -->


```{r item7}

```

<!--# Interprétation de l'item 7 -->


```{r item8}

```

<!--# Interprétation de l'item 8 -->


```{r item9}

```

<!--# Interprétation de l'item 9 -->


```{r item10}

```

<!--# Interprétation de l'item 10 -->


```{r item11}

```

<!--# Interprétation de l'item 11 -->


```{r item12}

```

<!--# Interprétation de l'item 12 -->


